site_name: Stochastic Dominance.jl
site_url: https://rajmadan96.github.io/StochasticDominance.jl
theme:
  name: material
  logo: assets/logo.png  
  favicon: assets/favicon.ico  # Optional

nav:
  - Home: index.md
  - Tutorials:
      - Introduction: tutorial/tutorial1.md
      - Scenario Trees: tutorial/tutorial2.md
          
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

repo_url: https://github.com/rajmadan96/StochasticDominance.jl.git
edit_uri: ""

plugins:
  - search
  - mkdocstrings
